# Generated by Django 5.2.7 on 2025-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pase',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pase',
            name='tipo',
            field=models.CharField(default='DESCONOCIDO', help_text='Tipo de pase', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
