# Generated by Django 5.2.7 on 2025-10-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_remove_pase_nombre_pase_tipo'),
        ('entradas', '0003_seed_initial_passes'),
    ]

    operations = [
    ]
